# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TL_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_show_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_show_camera.setGeometry(QtCore.QRect(190, 170, 1080, 720))
        self.label_show_camera.setStyleSheet("")
        self.label_show_camera.setText("")
        self.label_show_camera.setObjectName("label_show_camera")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(1440, 900, 131, 61))
        self.start_btn.setStyleSheet("font: 18pt \"Abaddon™\";")
        self.start_btn.setObjectName("start_btn")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(1670, 900, 131, 61))
        self.stop_btn.setStyleSheet("font: 18pt \"Abaddon™\";")
        self.stop_btn.setObjectName("stop_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 30, 1061, 81))
        self.label.setStyleSheet("font: 48pt \"Abaddon™\";")
        self.label.setObjectName("label")
        self.car_numberlabe = QtWidgets.QLabel(self.centralwidget)
        self.car_numberlabe.setGeometry(QtCore.QRect(1500, 420, 121, 16))
        self.car_numberlabe.setObjectName("car_numberlabe")
        self.car_numberlabe_2 = QtWidgets.QLabel(self.centralwidget)
        self.car_numberlabe_2.setGeometry(QtCore.QRect(1500, 450, 121, 16))
        self.car_numberlabe_2.setObjectName("car_numberlabe_2")
        self.car_numberlable_3 = QtWidgets.QLabel(self.centralwidget)
        self.car_numberlable_3.setGeometry(QtCore.QRect(1500, 480, 121, 16))
        self.car_numberlable_3.setObjectName("car_numberlable_3")
        self.car_numberlabe_4 = QtWidgets.QLabel(self.centralwidget)
        self.car_numberlabe_4.setGeometry(QtCore.QRect(1500, 510, 121, 16))
        self.car_numberlabe_4.setObjectName("car_numberlabe_4")
        self.car_number_1 = QtWidgets.QLabel(self.centralwidget)
        self.car_number_1.setGeometry(QtCore.QRect(1610, 420, 121, 16))
        self.car_number_1.setText("")
        self.car_number_1.setObjectName("car_number_1")
        self.car_number_3 = QtWidgets.QLabel(self.centralwidget)
        self.car_number_3.setGeometry(QtCore.QRect(1610, 480, 121, 16))
        self.car_number_3.setText("")
        self.car_number_3.setObjectName("car_number_3")
        self.car_number_2 = QtWidgets.QLabel(self.centralwidget)
        self.car_number_2.setGeometry(QtCore.QRect(1610, 450, 121, 16))
        self.car_number_2.setText("")
        self.car_number_2.setObjectName("car_number_2")
        self.car_number_4 = QtWidgets.QLabel(self.centralwidget)
        self.car_number_4.setGeometry(QtCore.QRect(1610, 510, 121, 16))
        self.car_number_4.setText("")
        self.car_number_4.setObjectName("car_number_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_btn.setText(_translate("MainWindow", "ON"))
        self.stop_btn.setText(_translate("MainWindow", "OFF"))
        self.label.setText(_translate("MainWindow", "智慧交通信号灯车辆统计演示"))
        self.car_numberlabe.setText(_translate("MainWindow", "路口一车辆："))
        self.car_numberlabe_2.setText(_translate("MainWindow", "路口二车辆："))
        self.car_numberlable_3.setText(_translate("MainWindow", "路口三车辆："))
        self.car_numberlabe_4.setText(_translate("MainWindow", "路口四车辆："))
